name: football_app
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  hive_flutter: ^1.1.0
  appsflyer_sdk: 
  url_launcher:
  overlay_support: ^2.1.0
  app_tracking_transparency: ^2.0.4
  share_plus:
  firebase_core: 
  firebase_remote_config:
  flutter_inappwebview: ^5.7.2+3
  flutter_local_notifications: ^9.8.0+1
  firebase_messaging: ^14.2.2
  firebase_analytics:
  reorderable_grid_view: ^2.2.8
  shared_preferences: ^2.2.3
  cached_network_image: 
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/puzzle/image_1/
    - assets/images/puzzle/image_2/
    - assets/images/puzzle/image_3/
    - assets/images/puzzle/image_4/
    - assets/icons/
